using LceLauncher.Models;

namespace LceLauncher.Services;

public static class BridgeConfigRenderer
{
    public static string Render(ServerEntry server)
    {
        if (server.Type != ServerType.JavaBridge || server.LocalBridgePort is null)
        {
            throw new InvalidOperationException("Bridge configs can only be generated for Java bridge servers.");
        }

        return $$"""
# ============================================================
# LCEBridge Configuration
# Generated by the LCE Launcher
# ============================================================

lce:
  address: 127.0.0.1
  port: {{server.LocalBridgePort.Value}}
  motd: "{{Escape(server.DisplayName)}}"
  max-players: 0

remote:
  address: {{server.RemoteAddress}}
  port: {{server.RemotePort}}
  auth-type: offline

floodgate:
  key-file: key.pem
  username-prefix: "."

world:
  world-size-limit: 0
  negative-y-handling: clamp
  view-distance: 0
  chunks-per-tick: 4

inventory:
  show-translated-names: true
  show-translated-lore: true
  lce-crafting-ui: true

performance:
  chunk-translation-threads: 0
  chunk-cache-enabled: true
  chunk-cache-size: 256
  async-compression: true
  live-tile-updates: false
  forward-chat: true

logging:
  level: info
  log-packets: false
  log-translation-failures: true
  packet-dump-enabled: false
  packet-dump-directory: dumps/

advanced:
  lan-broadcast: false
  lan-broadcast-port: 25566
  login-timeout: 600
  connection-timeout: 1200
  debug-scoreboard: false
""";
    }

    private static string Escape(string value) => value.Replace("\"", "\\\"");
}
