using LceLauncher.Models;

namespace LceLauncher.Services;

public static class BridgeConfigRenderer
{
    public static string Render(ServerEntry server, LauncherConfig launcherConfig, BridgeAuthContext? authContext = null)
    {
        if (server.Type != ServerType.JavaBridge || server.LocalBridgePort is null)
            throw new InvalidOperationException("Bridge configs can only be generated for Java bridge servers.");

        var authType = authContext is null ? "offline" : "online";
        var logLevel = NormalizeLogLevel(launcherConfig.ManagedBridgeLogLevel);
        var logPackets = launcherConfig.ManagedBridgeLogPackets ? "true" : "false";
        var onlineFields = authContext is null
            ? string.Empty
            : $"""
  minecraft-profile-id: "{Escape(authContext.MinecraftProfileId)}"
  minecraft-profile-name: "{Escape(authContext.MinecraftUsername)}"
  minecraft-access-token: "{Escape(authContext.MinecraftAccessToken)}"
""";

        return $$"""
# ============================================================
# LCEBridge Configuration — generated by LCE Launcher
# ============================================================

lce:
  address: 127.0.0.1
  port: {{server.LocalBridgePort.Value}}
  motd: "{{Escape(server.DisplayName)}}"
  max-players: 0

remote:
  address: {{server.RemoteAddress}}
  port: {{server.RemotePort}}
  auth-type: {{authType}}
{{onlineFields}}

floodgate:
  key-file: key.pem
  username-prefix: "."

world:
  world-size-limit: 0
  negative-y-handling: clamp
  view-distance: 0
  chunks-per-tick: 4

inventory:
  show-translated-names: true
  show-translated-lore: true
  lce-crafting-ui: true

performance:
  chunk-translation-threads: 0
  chunk-cache-enabled: true
  chunk-cache-size: 256
  async-compression: true
  live-tile-updates: true
  forward-chat: true

logging:
  level: {{logLevel}}
  log-packets: {{logPackets}}
  log-translation-failures: true
  packet-dump-enabled: false
  packet-dump-directory: dumps/

advanced:
  lan-broadcast: false
  lan-broadcast-port: 25566
  login-timeout: 600
  connection-timeout: 1200
  debug-scoreboard: false
""";
    }

    private static string NormalizeLogLevel(string? value)
    {
        var n = value?.Trim().ToLowerInvariant();
        return n is "trace" or "debug" or "info" or "warn" or "error" ? n : "info";
    }

    private static string Escape(string value) => value.Replace("\"", "\\\"");
}
